dist: trusty

language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac libglib2.0-bin
      libglib2.0-dev uuid-dev torque-client python3-pip intltool libgee-0.8-dev
      libxml2-dev
    - pip3 install --user meson
    - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
    - unzip ninja-linux.zip -d ${HOME}/.local/bin

before_script:
    - mkdir build
    - meson . build
    - ninja -C build -v

script:
    - meson test -v
    - DESTDIR=$(mktemp -d) ninja -C build -v install
