dist: trusty

language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac libglib2.0-bin
      libglib2.0-dev uuid-dev torque-client python3-pip intltool libgee-0.8-dev
      libxml2-dev
    - wget http://ftp.gnome.org/pub/gnome/sources/gxml/0.14/gxml-0.14.3.tar.xz
    - tar xvf gxml-0.14.3.tar.xz
    - cd gxml-0.14.3
    - ./configure --prefix=/usr && make && sudo make install && cd ..
    - pip3 install meson
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.1/ninja-linux.zip
    - sudo unzip ninja-linux.zip -d /usr/local/bin

before_script:
    - mkdir build
    - meson . build
    - ninja -C build -v

script:
    - mesontest -v
    - DESTDIR=$(mktemp -d) ninja -C build -v install
